version: "3.8"
services:
  myblog:
    build:
      context: .
    image: hexo-bohr:v1
    ports:
      - "4000:4000"
    environment:
      - LANG=C.UTF-8
    volumes:
      - source: ./blog/source
        target: /var/www/myblog/source
        type: bind
