# ---------------------------------------------------------------
# Layout
# ---------------------------------------------------------------
divisionLine: true
articleImgInCenter: true
showTags: true
showCategories: true
toTop:
  use: true
  icon: fa-pagelines
catalogBtn:
  use: true
  icon: fa-list-ul
excerpt: 500
footer: true
pages: 
  archives:
    link: "/archives"
    icon: "fa fa-file-text-o"
  about:
    link: "/about"
    icon: "fa fa-user-circle"
  rss:
    link: "/atom.xml"
    icon: "fa fa-rss"
color:
  deactive: '#37474f'
  active: '#006064'  


# ---------------------------------------------------------------
# Blog Info
# ---------------------------------------------------------------
# If your article have tags, it will also be contained in the article html page's head.
# For a single article, you can add description in it's front-matter，than this article has it's own html description.
# Otherwise it's html description will only contain your site description.(hexo/_config.yml, #site, description)
# Description loading order: page description->page excerpt->blog description. When one of them was loaded, all of the rest will not be loaded.
head:
  keywords: 


# ---------------------------------------------------------------
# Author Info
# ---------------------------------------------------------------
info:
  slogan: "我感激得很方先生肯为我表演口才。"
  avatarCard: true
img:
  # eg. site_logo: "/avatar.png"
  site_logo: '/a.jpg'
  avatar: '/a.jpg'
sns:
  email:
    link: "mailto:bohrasdf@gmail.com"
    icon: fa-envelope-o
  weibo:
    link: "https://weibo.com/209495952"
    icon: fa-weibo
  twitter:
    link: "https://twitter.com/leoric_ring"
    icon: fa-twitter
  instagram:
    link: "https://www.instagram.com/akarat_bo/"
    icon: fa-instagram


# ---------------------------------------------------------------
# Widget
# ---------------------------------------------------------------
# Now just for google_analytics(use: google_analytics, site_id: your tracking_id)
analytics:
    use: google_analytics
    site_id: UA-128594966-1
     
# Comment
# You can use disqus(use: disqus,shortname: your disqus shortname) or livere(use: livere, livereuid: your livereuid)
comment:
  use: 
  shortname: 
  livereuid: 
