nav:
  Home: /
  About: /about/
  Writing: /archives/
  Newsletter: http://linux.akarat.xyz
  Thoughts: https://thoughts.akarat.xyz

projects_url: https://github.com/bohrasd

customize:
    gravatar:
        email: bohrasdf@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon-192x192.png
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        telegram: https://t.me/origami_penguin
        github: https://github.com/bohrasd
        twitter: https://twitter.com/leoric_ring
        linkedin: https://www.linkedin.com/in/bohr-%E5%BC%A0%E5%93%B2%E6%BA%90-72604484/
    show_all_posts: false
    post_count: 20
    highlight: monokai

# RSS
rss:

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-128594966-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
